#ifndef _REDPLANT_CONFIG_HEADER_
#define _REDPLANT_CONFIG_HEADER_
//REDLIGHTS CONFIG FILE
//WRITTEN 3:05:30 PM
//#define REDLIGHT_FAST
//#define REDLIGHT_APPROX_D
//#define REDLIGHT_DO_EARLY_OUT
#endif
